# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: check
        name: Check code
        entry: just check
        language: system
        types: [python]
        pass_filenames: false
