name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Setup Python
        run: uv python install
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: check
        run: uv run ruff check .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Setup Python
        run: uv python install
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Run tests
        run: uv run pytest
